# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    npm install 
    mkdir publish 
    cp -r node_modules package.json server.js publish
  displayName: Install NodeJS Dependencies
  
- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.SourcesDirectory)/publish'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'ce99914a-0f7d-4c46-9ccc-e4d025115ea9/f0174cff-2623-4600-a29f-0eb8a06b0a0c'
    vstsFeedPackagePublish: 'catalogue'
    versionOption: 'patch'
    packagePublishDescription: 'RoboShop Catalogue'