apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  type: LoadBalancer
  selector:
    tier: catalogue
    build: "BUILDNO"
  ports:
    - protocol: TCP
      port: 7002
      targetPort: 7002
